services:
  frontend:
    build:
      context: ./chronos-pomodoro
      dockerfile: ../dockerfile
    ports:
      - "5173:5173"
    network_mode: "bridge"
    volumes:
      - ./chronos-pomodoro:/app
      - /app/node_modules
    environment:
    # Força o Vite a monitorar mudanças de arquivos dentro do container
      - WATCHPACK_POLLING-true